# fly.toml app configuration file generated for arekkutienda-admin on 2023-12-13T19:46:09-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "arekkutienda-admin"
primary_region = "qro"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
